module.exports = {
    frontend: [
        "React",
        "Next.js",
        "Angular",
        "Vue",
        "Svelte",
        "HTML",
        "CSS",
        "Tailwind CSS",
        "Bootstrap",
        "Material UI"
    ],
    backend: [
       "Node.js",
        "Express",
        "NestJS",
        "Spring Boot",
        "Laravel",
        "ASP.NET",
        "Django",
        "Flask",
        "Ruby",
        "FastAPI"
    ],
    
    devops: [
        "Docker",
        "Kubernetes",
        "Jenkins",
        "Ansible",
        "Github Actions",
        "Gitlab CI/CD",
        "Heroku",
        "Grafana",
        "Prometheus",
    ],
    databases: [
        "MongoDB",
        "MySQL",
        "PostgreSQL",
        "Oracle",
        "Microsoft SQL Server",
        "SQLite",
    ],
    cache : [
        "Redis",
        "Memcached",
        "MemSQL",
    ],
    queue: [
        "RabbitMQ",
        "Kafka",
        "ActiveMQ",
        "ZeroMQ",
        "Amazon SQS",
        "Google Cloud Pub/Sub",
        "Azure Service Bus",
    ],
    apiGateway: [
        "Kong",
        "NGINX",
        "AWS API Gateway",
        "Azure API Management",
        "Google API Gateway"
    ],
    thirdParty: [
        "Stripe",
        "Twilio",
        "Firebase",
        "Auth0",
        "Google Maps",
        "OpenAI",
        "SendGrid"
    ],
    cloudService: [
        "AWS Lambda",
        "Amazon S3",
        "Amazon EC2",
        "Amazon RDS",
        "Azure Blob Storage",
        "Cloud Run",
        "Cloud Functions",
        "Google Cloud Storage",
        "Google Cloud SQL",
        "Google Cloud Functions",
        "Google Cloud Firestore",
        "Google Cloud Datastore",
    ],
    dataScience: [
        "Pandas",
        "NumPy",
        "Matplotlib",
        "Seaborn",
        "Scikit-learn",
        "TensorFlow",
        "PyTorch",
    ],
    uiux: [
        "Figma",
        "Adobe XD",
        "Adobe Illustrator",
        "Adobe Photoshop",
        "Sketch",
        "InVision",
    ],
}